# Generated by Django 5.2.17 on 2026-09-21 02:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('document_type', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte')], default='NIT', max_length=20)),
                ('identification_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('client_type', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], default='JURIDICA', max_length=20)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('LEGAL', 'Documento Legal / Contractual'), ('POLIZA', 'Pólizas y Seguros'), ('SERVICIOS', 'Servicios Públicos'), ('FINANCIERO', 'Facturación y Pagos'), ('COMUNICACION', 'Comunicaciones y Solicitudes')], default='LEGAL', max_length=30)),
                ('requires_expiration', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo Documental',
                'verbose_name_plural': 'Tipos Documentales',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('property_address', models.CharField(max_length=255, verbose_name='Dirección de la Bodega / Inmueble')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('TERMINADO', 'Terminado'), ('EN_RENOVACION', 'En Renovación')], default='ACTIVO', max_length=30)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.client')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-start_date', 'contract_number'],
            },
        ),
        migrations.CreateModel(
            name='DigitalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_path', models.CharField(help_text='Prefijo en S3/MinIO para este expediente', max_length=500)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_record', to='core.contract')),
            ],
            options={
                'verbose_name': 'Expediente Digital',
                'verbose_name_plural': 'Expedientes Digitales',
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='contract_end_date_gte_start_date'),
        ),
    ]
