# Generated by Django 5.2.17 on 2026-09-21 02:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia de Radicación',
                'verbose_name_plural': 'Secuencias de Radicación',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Número de Radicado')),
                ('file_path', models.CharField(help_text='URI del objeto en S3 / MinIO', max_length=1000)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, help_text='Checksum SHA-256', max_length=64)),
                ('file_size_bytes', models.BigIntegerField()),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('source_channel', models.CharField(choices=[('FISICO_ESCANEADO', 'Documento Físico Escaneado'), ('DIGITAL_INTERNO', 'Digital Cargado por Personal'), ('PORTAL_WEB', 'Radicado por Cliente en Portal Web'), ('CORREO', 'Ingreso por Correo Electrónico')], default='DIGITAL_INTERNO', max_length=30)),
                ('processing_status', models.CharField(choices=[('RECIBIDO', 'Recibido / En cola'), ('PROCESANDO', 'Procesando en Celery'), ('REQUIERE_REVISION', 'Requiere Validación Humana (HITL)'), ('PROCESADO', 'Clasificado y Archivado'), ('FALLIDO', 'Error de Procesamiento')], db_index=True, default='RECIBIDO', max_length=30)),
                ('ai_extracted_data', models.JSONField(blank=True, default=dict)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, db_index=True, null=True)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('external_sender_name', models.CharField(blank=True, help_text='Nombre del remitente externo si vino del portal', max_length=255)),
                ('digital_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.digitalrecord')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documenttype')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Radicado',
                'verbose_name_plural': 'Documentos Radicados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CARGA', 'Carga y Radicación'), ('CLASIFICACION_IA', 'Clasificación con IA'), ('VALIDACION_HUMANA', 'Aprobación o Ajuste Manual'), ('ACTUALIZACION_METADATOS', 'Edición de Metadatos'), ('CONSULTA_VISUAL', 'Visualización en Visor Web'), ('DESCARGA', 'Descarga de Archivo')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='documents.document')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['processing_status', '-created_at'], name='doc_status_created_idx'),
        ),
    ]
