# Generated by Django 5.2.17 on 2026-09-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auditlog_immutability_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CARGA', 'Carga y Radicación'), ('CLASIFICACION_IA', 'Clasificación con IA'), ('VALIDACION_HUMANA', 'Aprobación o Ajuste Manual'), ('ACTUALIZACION_METADATOS', 'Edición de Metadatos'), ('CONSULTA_VISUAL', 'Visualización en Visor Web'), ('DESCARGA', 'Descarga de Archivo'), ('ALERTA_VENCIMIENTO', 'Alerta de Vencimiento')], db_index=True, max_length=30),
        ),
    ]
